### ISSUE TITLE
[Feature Request] Speed Units in KiloByte and MegaByte

### ISSUE THREAD

**Issue by tazihad** [LeeVD/plasma-applet-net-bandwidth-monitor#1]
We need more option. KB/s and MB/s.

**Comment by LeeVD** [comment]
In the settings section, changing the dropdown form 'bits' to 'bytes' should give you KB and MB. Let me know if it works for you?
![image](https://user-images.githubusercontent.com/72889808/210446156-60f56b9f-7807-424e-ac43-8e3b151e04be.png)

**Comment by tazihad** [comment]
@LeeVD 
Hi. Applet still doesn't work. `Bytes` does nothing. There's no way my internet speed is that high.  
![Screenshot_20230117_002149](https://user-images.githubusercontent.com/19417232/212744552-fdfaa4e8-a1a6-4683-b3d7-74f9e0708d3a.png)

**Comment by LeeVD** [comment]
Are you using the new version?  There was indeed an error in v0.1 with the bits to bytes conversion.  It has been fixed in v0.1.1 release yesterday.

**Comment by LeeVD** [comment]
Version 0.2 just released. It should solve the issue you experienced in the last version. The Bytes option has been completely rewritten and uses data gather by DBUS rather than a code conversion from bits.  let me know how you get on.

**Comment by tazihad** [comment]
@LeeVD I just tried 0.2. It works now.
