### ISSUE TITLE
Floating point error

### ISSUE THREAD

**Issue by Zzombiee2361** [LeeVD/plasma-applet-net-bandwidth-monitor#16]
I could reliably reproduce this bug using this setting:
- Update interval: 3s
- Interval data relay: Average
- Speed units: Bytes

Seems like an issue when calculating average network, and the result bypass decimal place setting

![image](https://user-images.githubusercontent.com/37852137/225323473-ae1075ec-f053-49d6-84a0-6a3bb707aa3f.png)

**Comment by LeeVD** [comment]
@Zzombiee2361 thanks for the feedback.  I'll look into this issue. Ta.
