### ISSUE TITLE
[Bug report] `Accumulated` mode stats double the actual value

### ISSUE THREAD

**Issue by CatEricka** [LeeVD/plasma-applet-net-bandwidth-monitor#19]
## Expected Behavior:

`Update interval` set to 1, `Average` mode and `Accumulated` mode should show the same value. (for obvious math reasons)

## Current Behavior

The `Accumulated` mode shows twice the value shown by the `Average` mode.

## Possible Solution

Merge #15

**Comment by LeeVD** [comment]
Hi @CatEricka 
You are correct in that `Average` has a mathematical formula that averages out the bandwidth and that, as we discussed in other trackers, is implemented.  The `Accumulated` option is not the same as average and has a alternative formula, hence the different results.  With help from your input i added a full explanation in the 'info' section of the general settings page, hopefully that should resolve any confusion on a user.
I'm going to set this as closed but message if I've got something wrong here.

Ta.
