### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by tazihad** [LeeVD/plasma-applet-net-bandwidth-monitor#3]
There are 3 missing icons. I am using Fedora 37 KDE.

![Screenshot_20221229_074450](https://user-images.githubusercontent.com/19417232/209892815-7f227a93-32c0-4490-8364-3d3d4a90ab0a.png)

**Comment by luisbocanegra** [comment]
Definitely  a font issue, maybe you should add a note for the users to use a different font (e.g. a nerd font https://github.com/ryanoasis/nerd-fonts), in case they face this problem. Maybe you could include a custom stripped font with the plasmoid just for the glyphs? (taking license into account of course)

**Comment by LeeVD** [comment]
Note added Luis. I've done a little research and think the custom stripped font with the plasmoid just for the glyphs would be the best/simple solution.  Working on the update.

**Comment by LeeVD** [comment]
I think I've fixed the icon missing in the dropdown issue.  Tested on latest Fedora KDE edition with v0.1.1 widget and icons are present.  Let me know if this is not the case.

![Screenshot_20230115_180135](https://user-images.githubusercontent.com/72889808/212572356-6ad28acf-afb0-4bba-8f39-461a37c8a69d.png)

**Comment by luisbocanegra** [comment]
I have an idea, an option to manually set the upload/download text/icons that will be displayed in the widget :)

**Comment by LeeVD** [comment]
I think this should be doable, once I've fixed all the issues :) 
How much text space would you expect?

**Comment by LeeVD** [comment]
Custom icons makes sense, maybe if someone wanted a semicolon as a divider, so 2 or 3 characters length.  If someone wanted a string of text i guess that would need to be managed some how, maybe limit the number characters and which characters are allowed?  The widget 'should' expand to accommodate the text length but then again, I've seen the size not correctly fit the icons i have used. I'm guessing this is something to do with the icon reporting what size it should be incorrectly.  Will look in to it, thanks.

**Comment by luisbocanegra** [comment]
> Custom icons makes sense, maybe if someone wanted a semicolon as a divider, so 2 or 3 characters length. If someone wanted a string of text i guess that would need to be managed some how, maybe limit the number characters and which characters are allowed? 

A 2-3 limit seems reasonable to me

> The widget 'should' expand to accommodate the text length but then again, I've seen the size not correctly fit the icons i have used. I'm guessing this is something to do with the icon reporting what size it should be incorrectly. 

Yeah that's a very common issue with some glyphs in patched fonts like nerd fonts so alowwing an extra space in the text boxes would make sense for those cases.

**Comment by tazihad** [comment]
Icons seems fixed in 0.2 version.
