### ISSUE TITLE
Network picker loose settings

### ISSUE THREAD

**Issue by leuchtrakete666** [LeeVD/plasma-applet-net-bandwidth-monitor#5]
every time i am on a new network - i use the plasmaoid with a laptop - it loose the setting. it also don't remember previous used networks.

would be great if its possible to choose just the physical interface it should be bound to.

**Comment by LeeVD** [comment]
I was looking at some of the code today related to the interfaces being added to the widget.  From what i can tell, if you are moving between networks, in your case APs, then the behaviour is currently 'correct'.  It refreshes the interface list and doesn't remember the previous or enabled int settings.  
I had noticed that when you first install the widget, you have to go in to setting (Network Interface(s) and check the interface(s) you want to be monitored.  I'll be changing this to auto enable in the next release.  I'm not sure accumulated traffic is actually working so will be trying to fix that before hand.  I guess this would solve your issue?  You would of course need to manually disable any interface you didn't want monitored.

**Comment by leuchtrakete666** [comment]
super. i wait for your next release. and thank you.

**Comment by LeeVD** [comment]
Version 0.2 just released.  It should solve the issue you experienced in the last version.  let me know how you get on.

**Comment by LeeVD** [comment]
Closing as this issue should be resolved now.
